// -*- C++ -*- generated by wxGlade 0.6.1 on Wed Jan  9 19:01:12 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef CONVERTDIALOG_H
#define CONVERTDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade


class ConvertDialog: public wxDialog {
public:
    // begin wxGlade: ConvertDialog::ids
    // end wxGlade

    ConvertDialog(wxWindow* parent);


    double  convert_from() const;
    double  convert_to() const;
    wxString convert_to_str() const;
    bool    size() const;
    bool    fontsize() const;
    bool    stretchposition() const;

private:
    // begin wxGlade: ConvertDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ConvertDialog::attributes
    wxStaticBox* sizer_6_staticbox;
    wxStaticBox* sizer_5_staticbox;
    wxStaticBox* sizer_4_staticbox;
    wxStaticText* label_1;
    wxChoice* m_aspectratio_from;
    wxStaticText* label_1_copy;
    wxChoice* m_aspectratio_to;
    wxCheckBox* m_fontsize;
    wxCheckBox* m_size;
    wxCheckBox* m_stretchposition;
    wxButton* button_1;
    wxButton* button_2;
    // end wxGlade
}; // wxGlade: end class


#endif // CONVERTDIALOG_H
