// -*- C++ -*- generated by wxGlade 0.6.1 on Wed Dec 05 16:09:56 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef ELEMENTSCTRLBASE_H
#define ELEMENTSCTRLBASE_H

// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class ElementsCtrlBase: public wxPanel {
public:
    // begin wxGlade: ElementsCtrlBase::ids
    // end wxGlade

    ElementsCtrlBase(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: ElementsCtrlBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ElementsCtrlBase::attributes
    wxButton* button_4;
    wxButton* button_5;
    wxTreeCtrl* tree_ctrl_2;
    // end wxGlade
}; // wxGlade: end class


#endif // ELEMENTSCTRLBASE_H
