// -*- C++ -*- generated by wxGlade 0.6.1 on Wed Dec 05 16:09:56 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef ELEMENTSCTRLBASE_H
#define ELEMENTSCTRLBASE_H

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#include "elementslistctrl.h"
#include "elementbase.h"
#include "hudfilebase.h"

class ElementsCtrlBase: public wxPanel {
  
public:
    // begin wxGlade: ElementsCtrlBase::ids
    // end wxGlade

    ElementsCtrlBase(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);


    virtual void clear();
    virtual void append( ElementBase *el );
    virtual void list_refresh( const HudFileBase::elements_type& elements );

    virtual void OnSelectionChanged();

    ElementsListCtrl* elementslistctrl() { return m_listctrl; }

  private:
    void OnBtnCopy( wxCommandEvent& );
    void OnBtnPaste( wxCommandEvent& );

private:
    // begin wxGlade: ElementsCtrlBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ElementsCtrlBase::attributes
    wxButton* m_btn_insertdefault;
    wxButton* m_btn_insertpredecorate;
    wxButton* m_btn_insertpostdecorate;
    ElementsListCtrl* m_listctrl;
    wxBitmapButton* m_btn_copy;
    wxBitmapButton* m_btn_paste;
    // end wxGlade
    /* FIXMEHERE
    ElementsListCtrl* m_listctrl;
    */

    DECLARE_EVENT_TABLE()
}; // wxGlade: end class


#endif // ELEMENTSCTRLBASE_H
