// -*- C++ -*- generated by wxGlade 0.6.1 on Wed Dec 05 16:09:56 2007

#include "elementsctrlbase.h"
#include "elementbase.h"

// begin wxGlade: ::extracode

// end wxGlade


ElementsCtrlBase::ElementsCtrlBase(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: ElementsCtrlBase::ElementsCtrlBase
    m_listctrl = new ElementsListCtrl(this);

    set_properties();
    do_layout();
    // end wxGlade
}

void ElementsCtrlBase::append( ElementBase *el )
{
  m_listctrl->InsertItem(0, el->name());//m_listctrl->GetItemCount()-1, el->name());
}

void ElementsCtrlBase::clear()
{
  m_listctrl->ClearAll();
}


void ElementsCtrlBase::set_properties()
{
    // begin wxGlade: ElementsCtrlBase::set_properties
    // end wxGlade
  m_listctrl->InsertColumn(0, _("On?"), wxLIST_FORMAT_LEFT, 20);
  m_listctrl->InsertColumn(1, _("Name"), wxLIST_FORMAT_LEFT, 200);
}


void ElementsCtrlBase::do_layout()
{
    // begin wxGlade: ElementsCtrlBase::do_layout
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    sizer_3->Add(m_listctrl, 1, wxEXPAND, 0);
    SetSizer(sizer_3);
    sizer_3->Fit(this);
    // end wxGlade
}

