// -*- C++ -*- generated by wxGlade 0.6.1 on Wed Dec 05 16:09:56 2007

#include "elementsctrlbase.h"
#include "elementbase.h"

// begin wxGlade: ::extracode

// end wxGlade


ElementsCtrlBase::ElementsCtrlBase(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: ElementsCtrlBase::ElementsCtrlBase
    m_listctrl = new ElementsListCtrl(this);

    set_properties();
    do_layout();
    // end wxGlade
}

void ElementsCtrlBase::append( ElementBase *el )
{
  long idx = m_listctrl->InsertItem(m_listctrl->GetItemCount(), wxT(""));//m_listctrl->GetItemCount()-1, el->name());
  m_listctrl->SetItem( idx, 0, wxEmptyString, 1 );
  m_listctrl->SetItem( idx, 1, el->name(), -1 );
}

void ElementsCtrlBase::clear()
{
  m_listctrl->DeleteAllItems();
}

void ElementsCtrlBase::list_refresh( const HudFileBase::elements_type& elements )
{
  clear();
  for( HudFileBase::cit_elements cit = elements.begin(); cit != elements.end(); ++cit )
  {
    append(*cit);
  }
}


void ElementsCtrlBase::set_properties()
{
    // begin wxGlade: ElementsCtrlBase::set_properties
    // end wxGlade
}


void ElementsCtrlBase::do_layout()
{
    // begin wxGlade: ElementsCtrlBase::do_layout
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    sizer_3->Add(m_listctrl, 1, wxEXPAND, 0);
    SetSizer(sizer_3);
    sizer_3->Fit(this);
    // end wxGlade
}

