// -*- C++ -*- generated by wxGlade 0.6.1 on Wed Dec 05 16:09:56 2007

#include <wx/wx.h>
#include <wx/image.h>

#ifndef ELEMENTSCTRLBASE_H
#define ELEMENTSCTRLBASE_H

// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#include "elementslistctrl.h"
#include "elementbase.h"
#include "hudfilebase.h"
#include <list>

typedef std::list<int>  indecies_type;
typedef indecies_type::iterator it_indecies;
typedef indecies_type::const_iterator cit_indecies;

class ElementsCtrlBase: public wxPanel
{
  public:
    

  public:
    // begin wxGlade: ElementsCtrlBase::ids
    // end wxGlade

    ElementsCtrlBase(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);


    virtual void clear();
    virtual void append( ElementBase *el );
    virtual void list_refresh( const elements_type& elements );

    virtual void OnSelectionChanged();
    //virtual void OnMouseDClick( wxMouseEvent& ev );

    ElementsListCtrl* elementslistctrl() { return m_listctrl; }

    indecies_type&  selected_indecies() { return m_selidx; }
    elements_type&  selected_elements() { return m_selels; }

    bool            is_selected( const ElementBase* const el) const;

  protected:
    /// an ordered list (by idx) of selected indecies
    indecies_type   m_selidx;
    /// an ordered list (by idx) of selected elements
    elements_type   m_selels;

    /// update m_selidx and m_selels according to current selection
    void update_selection();


  private:
    void OnBtnCopy( wxCommandEvent& );
    void OnBtnPaste( wxCommandEvent& );

private:
    // begin wxGlade: ElementsCtrlBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ElementsCtrlBase::attributes
    wxButton* m_btn_insertdefault;
    wxButton* m_btn_insertpredecorate;
    wxButton* m_btn_insertpostdecorate;
    ElementsListCtrl* m_listctrl;
    wxBitmapButton* m_btn_copy;
    wxBitmapButton* m_btn_paste;
    // end wxGlade
    /* FIXMEHERE
    ElementsListCtrl* m_listctrl;
    */

    DECLARE_EVENT_TABLE()
}; // wxGlade: end class


#endif // ELEMENTSCTRLBASE_H
