#ifndef __EVENTIDS_H__
#define __EVENTIDS_H__

enum
{
	ID_BTN_Q4MAX = wxID_HIGHEST+1,
	ID_BTN_CPMA,

  ID_BTN_INSERTDEFAULT,
  ID_BTN_INSERTPREDECORATE,
  ID_BTN_INSERTPOSTDECORATE,
  ID_BTN_COPY,
  ID_BTN_PASTE,

  ID_MENU_TOOLS_GAMESELECTION,
  ID_MENU_TOOLS_PREFERENCES,

  ID_MENU_VIEW_DEFAULTPERSPECTIVE,
  ID_MENU_VIEW_CONFIGPREVIEW,
  ID_MENU_VIEW_TOOLBAR_FILE,


  ID_NOTEBOOK_PROPERTIES,


  ID_LISTCTRL_ELEMENTS,
  ID_TEXTCTRL_CONFIGPREVIEW
};

#endif //  __EVENTIDS_H__
