#ifndef __EVENTIDS_H__
#define __EVENTIDS_H__

enum
{
	ID_BTN_Q4MAX = wxID_HIGHEST+1,
	ID_BTN_CPMA,

  ID_BTN_INSERTDEFAULT,
  ID_BTN_INSERTPREDECORATE,
  ID_BTN_INSERTPOSTDECORATE,
  ID_BTN_COPY,
  ID_BTN_PASTE,

  ID_BTN_ELEMENT_ENABLE,
  ID_BTN_ELEMENT_DISABLE,

  ID_BTN_ALIGN_LEFT,
  ID_BTN_ALIGN_CENTER,
  ID_BTN_ALIGN_RIGHT,
  ID_BTN_ALIGN_TOP,
  ID_BTN_ALIGN_MIDDLE,
  ID_BTN_ALIGN_BOTTOM,

  ID_MENU_TOOLS_SWITCHGAME,
  ID_MENU_TOOLS_PREFERENCES,

  ID_MENU_VIEW_DEFAULTPERSPECTIVE,
  ID_MENU_VIEW_GRID,
  /// all the panes that can be switched on/off
  /// keep first and last in order as we add evthandler with range
  /// @{
  ID_MENU_VIEW_CONFIGPREVIEW,
  ID_MENU_VIEW_TOOLBAR_FILE,
  /// @}

  ID_MENU_HELP_UPDATE,


  ID_NOTEBOOK_PROPERTIES,


  ID_LISTCTRL_ELEMENTS,
  ID_TEXTCTRL_CONFIGPREVIEW
};

#endif //  __EVENTIDS_H__
