#ifndef EVENTIDS_H
#define EVENTIDS_H

enum
{
	ID_BTN_Q4MAX = wxID_HIGHEST+1,
	ID_BTN_CPMA,

  ID_BTN_INSERT,
  ID_PASTE_WITHRECT,

  ID_BTN_ELEMENT_ENABLE,
  ID_BTN_ELEMENT_DISABLE,

  ID_BTN_ALIGN_LEFT,
  ID_BTN_ALIGN_CENTER,
  ID_BTN_ALIGN_RIGHT,
  ID_BTN_ALIGN_TOP,
  ID_BTN_ALIGN_MIDDLE,
  ID_BTN_ALIGN_BOTTOM,

  ID_BTN_SELECTGAMEDIR,

  ID_MENU_TOOLS_SWITCHGAME,
  ID_MENU_TOOLS_CONVERT,
  ID_MENU_TOOLS_SNAPELEMENTS,
  ID_MENU_TOOLS_SNAPGRID,
  ID_MENU_TOOLS_PREFERENCES,

  ID_MENU_VIEW_DEFAULTPERSPECTIVE,
  ID_MENU_VIEW_GRID,
  /// all the panes that can be switched on/off
  /// keep first and last in order as we add evthandler with range
  /// @{
  ID_MENU_VIEW_CONFIGPREVIEW,
  ID_MENU_VIEW_TOOLBAR_FILE,
  /// @}
  ID_MENU_VIEW_FOCUSELEMENTS,
  ID_MENU_VIEW_FOCUSHUD,
  ID_MENU_VIEW_FOCUSPROPERTIES,

  ID_MENU_HELP_UPDATE,
  ID_MENU_HELP_TIP,


  ID_NOTEBOOK_PROPERTIES,

  ID_LISTCTRL_ELEMENTS,
  ID_TEXTCTRL_CONFIGPREVIEW,

  ID_LISTCTRL_PAKFILEDIALOG,
  ID_BTN_PAKFILEDLG_GODIRUP,

  ID_INSERT_NOTUNIQ,
  ID_INSERT_NOTUNIQ_END = ID_INSERT_NOTUNIQ+9
};

#endif //  EVENTIDS_H

