// -*- C++ -*- generated by wxGlade 0.6.1 on Thu Dec 06 10:11:23 2007

#include "GameSelectionDialog.h"
#include "common.h"

#include "xpm/icons/cpma48.xpm"
#include "xpm/icons/q4max48.xpm"

BEGIN_EVENT_TABLE(GameSelectionDialog, wxDialog)
  EVT_BUTTON(ID_BTN_CPMA, GameSelectionDialog::OnBtnCPMA)
  EVT_BUTTON(ID_BTN_Q4MAX, GameSelectionDialog::OnBtnQ4MAX)
END_EVENT_TABLE()

// begin wxGlade: ::extracode

// end wxGlade


GameSelectionDialog::GameSelectionDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
  /* FIXMEHERE
    bitmap_button_2 = new wxBitmapButton(this, ID_BTN_CPMA, wxBitmap(cpma48_xpm));
    bitmap_button_3 = new wxBitmapButton(this, ID_BTN_Q4MAX, wxBitmap(q4max48_xpm));
  */
    // begin wxGlade: GameSelectionDialog::GameSelectionDialog
    bitmap_button_2 = new wxBitmapButton(this, ID_BTN_CPMA, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\cpma48.xpm"), wxBITMAP_TYPE_ANY));
    bitmap_button_3 = new wxBitmapButton(this, ID_BTN_Q4MAX, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\q4max48.xpm"), wxBITMAP_TYPE_ANY));
    label_2 = new wxStaticText(this, wxID_ANY, wxT("CPMA"));
    label_3 = new wxStaticText(this, wxID_ANY, wxT("Q4MAX"));
    m_startup_gameselection = new wxCheckBox(this, wxID_ANY, wxT("Do not ask me again (can be changed in Tools->Game..."));

    set_properties();
    do_layout();
    // end wxGlade
}


void GameSelectionDialog::set_properties()
{
    // begin wxGlade: GameSelectionDialog::set_properties
    bitmap_button_2->SetSize(bitmap_button_2->GetBestSize());
    bitmap_button_3->SetSize(bitmap_button_3->GetBestSize());
    // end wxGlade
}


void GameSelectionDialog::do_layout()
{
    // begin wxGlade: GameSelectionDialog::do_layout
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(2, 2, 20, 50);
    grid_sizer_1->Add(bitmap_button_2, 0, 0, 0);
    grid_sizer_1->Add(bitmap_button_3, 0, 0, 0);
    grid_sizer_1->Add(label_2, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    grid_sizer_1->Add(label_3, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_2->Add(grid_sizer_1, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 20);
    sizer_2->Add(m_startup_gameselection, 0, wxALL, 5);
    SetSizer(sizer_2);
    sizer_2->Fit(this);
    Layout();
    // end wxGlade
}



void GameSelectionDialog::OnBtnCPMA( wxCommandEvent& )
{
  EndModal(ID_BTN_CPMA);
}

void GameSelectionDialog::OnBtnQ4MAX( wxCommandEvent& )
{
  EndModal(ID_BTN_Q4MAX);
}
