// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Sep 02 12:45:11 2006

#ifndef OPTIONALMESSAGEDIALOG_H
#define OPTIONALMESSAGEDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/artprov.h>

#include <wx/statline.h>

#include <map>
#include <list>

/// Order of use:
///  - ctor
///  - add_button
///  -
class OptionalMessageDialog: public wxDialog
{
  public:


    /// @arg name         An unique name
    /// @arg saveid       Which id we store (in prefs) if a user decides to not show it anymore, use wxID_ANY for the user's pressed button
    OptionalMessageDialog( const wxString& name, int saveid = wxID_ANY, wxArtID bitmapid = wxART_QUESTION );
    /// create it.
    virtual bool Create(wxWindow* parent, const wxString& msg, const wxString& title = wxT(""), int id = wxID_ANY, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize );

    virtual int ShowModal();
    virtual bool Show( bool show =true );

    void set_message( const wxString& msg );

    // wxGTK button order is No|Cancel|Yes
    void add_button( const wxString& text, int id );
    void add_button_yesno();

  protected:
    void OnButton( wxCommandEvent& ev );


  private:
    void set_properties();
    void do_layout();

  protected:
    int   m_saveid;
    int   m_storedid;
    wxString m_name; ///< unique name this dialog is identified with, also used in prefs saving.
  
    bool m_created; ///< in ShowModal and Show the dialog must have been created, we track it with this.

    wxArtID m_bitmapid;

    // displayedname -> id
    std::map<wxString, int> m_buttondefs;
    std::list<wxButton*> m_buttons;

    wxStaticText* m_message;
    wxStaticLine* m_horiz_line;
    wxCheckBox* m_shownomore;
};


#endif // OPTIONALMESSAGEDIALOG_H
