// -*- C++ -*- generated by wxGlade 0.6.1 on Sat Dec 08 17:28:33 2007

#include "PositionPropertiesCtrl.h"

// begin wxGlade: ::extracode

// end wxGlade


PositionPropertiesCtrl::PositionPropertiesCtrl(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: PositionPropertiesCtrl::PositionPropertiesCtrl
    sizer_8_staticbox = new wxStaticBox(this, -1, wxT("Position"));
    checkbox_1 = new wxCheckBox(this, wxID_ANY, wxT("&Overwrite"));
    label_1 = new wxStaticText(this, wxID_ANY, wxT("X"));
    spin_ctrl_1 = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    label_4 = new wxStaticText(this, wxID_ANY, wxT("Y"));
    spin_ctrl_2 = new wxSpinCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0, 100);
    bitmap_button_5 = new wxBitmapButton(this, wxID_ANY, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\align_left.xpm"), wxBITMAP_TYPE_ANY));
    bitmap_button_6 = new wxBitmapButton(this, wxID_ANY, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\align_center.xpm"), wxBITMAP_TYPE_ANY));
    bitmap_button_7 = new wxBitmapButton(this, wxID_ANY, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\align_right.xpm"), wxBITMAP_TYPE_ANY));
    bitmap_button_8 = new wxBitmapButton(this, wxID_ANY, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\align_top.xpm"), wxBITMAP_TYPE_ANY));
    bitmap_button_9 = new wxBitmapButton(this, wxID_ANY, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\align_middle.xpm"), wxBITMAP_TYPE_ANY));
    bitmap_button_10 = new wxBitmapButton(this, wxID_ANY, wxBitmap(wxT("E:\\projects\\cpp\\superhudeditor\\src\\xpm\\icons\\align_bottom.xpm"), wxBITMAP_TYPE_ANY));
    label_5 = new wxStaticText(this, wxID_ANY, wxT("Use the arrow keys to move the element"));

    set_properties();
    do_layout();
    // end wxGlade
}


void PositionPropertiesCtrl::set_properties()
{
    // begin wxGlade: PositionPropertiesCtrl::set_properties
    bitmap_button_5->SetSize(bitmap_button_5->GetBestSize());
    bitmap_button_6->SetSize(bitmap_button_6->GetBestSize());
    bitmap_button_7->SetSize(bitmap_button_7->GetBestSize());
    bitmap_button_8->SetSize(bitmap_button_8->GetBestSize());
    bitmap_button_9->SetSize(bitmap_button_9->GetBestSize());
    bitmap_button_10->SetSize(bitmap_button_10->GetBestSize());
    // end wxGlade
}


void PositionPropertiesCtrl::do_layout()
{
    // begin wxGlade: PositionPropertiesCtrl::do_layout
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_8 = new wxStaticBoxSizer(sizer_8_staticbox, wxVERTICAL);
    wxFlexGridSizer* grid_sizer_2 = new wxFlexGridSizer(2, 2, 5, 5);
    wxBoxSizer* sizer_13 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_12 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    sizer_6->Add(checkbox_1, 0, 0, 0);
    sizer_9->Add(label_1, 0, 0, 0);
    sizer_9->Add(spin_ctrl_1, 0, 0, 0);
    grid_sizer_2->Add(sizer_9, 1, wxEXPAND, 0);
    sizer_10->Add(label_4, 0, 0, 0);
    sizer_10->Add(spin_ctrl_2, 0, 0, 0);
    grid_sizer_2->Add(sizer_10, 1, wxEXPAND, 0);
    sizer_12->Add(bitmap_button_5, 0, 0, 0);
    sizer_12->Add(bitmap_button_6, 0, 0, 0);
    sizer_12->Add(bitmap_button_7, 0, 0, 0);
    grid_sizer_2->Add(sizer_12, 1, wxALL|wxALIGN_CENTER_HORIZONTAL, 3);
    sizer_13->Add(bitmap_button_8, 0, 0, 0);
    sizer_13->Add(bitmap_button_9, 0, 0, 0);
    sizer_13->Add(bitmap_button_10, 0, 0, 0);
    grid_sizer_2->Add(sizer_13, 1, wxALL|wxALIGN_CENTER_HORIZONTAL, 3);
    sizer_8->Add(grid_sizer_2, 1, wxEXPAND, 0);
    sizer_8->Add(label_5, 0, 0, 0);
    sizer_6->Add(sizer_8, 0, wxEXPAND, 0);
    SetSizer(sizer_6);
    sizer_6->Fit(this);
    // end wxGlade
}

