// -*- C++ -*- generated by wxGlade 0.6.1 on Tue Jan 08 19:26:19 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade


#ifndef PREFSDIALOG_TMP_H
#define PREFSDIALOG_TMP_H


// begin wxGlade: ::extracode
// end wxGlade






class advanced2_prefs: public wxDialog {
public:
    // begin wxGlade: advanced2_prefs::ids
    // end wxGlade

    advanced2_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: advanced2_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: advanced2_prefs::attributes
    // end wxGlade
}; // wxGlade: end class

class misc_prefs: public wxDialog {
public:
    // begin wxGlade: misc_prefs::ids
    // end wxGlade

    misc_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: misc_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: misc_prefs::attributes
    wxStaticBox* sizer_7_staticbox;
    wxStaticBox* sizer_2_staticbox;
    wxStaticBox* sizer_1_staticbox;
    wxStaticText* misc_title;
    wxCheckBox* m_save_backup;
    wxCheckBox* m_startup_load;
    wxStaticText* label_14;
    wxButton* button_1;
    wxCheckBox* m_elements_collections;
    // end wxGlade
}; // wxGlade: end class


class advanced_prefs: public wxDialog {
public:
    // begin wxGlade: advanced_prefs::ids
    // end wxGlade

    advanced_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: advanced_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: advanced_prefs::attributes
    wxStaticText* advanced_title;
    wxStaticText* m_view_dragthreshold;
    wxSpinCtrl* spin_ctrl_1;
    wxStaticText* label_15;
    wxSpinCtrl* m_view_snapthreshold;
    // end wxGlade
}; // wxGlade: end class


class cpma_prefs: public wxDialog {
public:
    // begin wxGlade: cpma_prefs::ids
    // end wxGlade

    cpma_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: cpma_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: cpma_prefs::attributes
    wxStaticBox* sizer_5_staticbox;
    wxStaticBox* sizer_3_staticbox;
    wxStaticText* cpma_title;
    wxStaticText* label_13;
    wxTextCtrl* m_q3_gamedir;
    wxButton* button_2;
    wxStaticText* label_12;
    wxTextCtrl* m_q3_background;
    wxButton* button_2_copy;
    wxCheckBox* m_q3_background_usedefault;
    // end wxGlade
}; // wxGlade: end class

class display_prefs: public wxPanel {
public:
    // begin wxGlade: display_prefs::ids
    // end wxGlade

    display_prefs(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: display_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: display_prefs::attributes
    wxStaticBox* helper_styler_staticbox;
    wxStaticBox* grid_styler_staticbox;
    wxStaticBox* ar_styler_staticbox;
    wxStaticText* display_title;
    wxStaticText* label_3;
    wxChoice* m_view_aspectratio;
    wxStaticText* label_1;
    wxTextCtrl* m_view_aspectratioX;
    wxStaticText* label_2;
    wxTextCtrl* m_view_aspectratioY;
    wxStaticText* label_4;
    wxSpinCtrl* m_view_gridX;
    wxStaticText* label_5;
    wxSpinCtrl* m_view_gridY;
    wxStaticText* label_6;
    wxButton* m_view_gridcolor;
    wxStaticText* label_7;
    wxSlider* m_view_gridcolor_alpha;
    wxStaticText* label_10;
    wxStaticText* label_8;
    wxStaticText* label_9;
    wxButton* m_view_fill_selected;
    wxStaticText* labelfa;
    wxSlider* m_view_fill_selected_alpha;
    wxStaticText* label_11;
    wxButton* m_view_border_selected;
    wxStaticText* labeloa;
    wxSlider* m_view_border_selected_alpha;
    wxStaticText* label_8_copy;
    wxStaticText* label_9_copy;
    wxButton* m_view_fill;
    wxStaticText* labelaeijfafe;
    wxSlider* m_view_fill_alpha;
    wxStaticText* label_11_copy;
    wxButton* m_view_border;
    wxStaticText* labelahosehjfija;
    wxSlider* m_view_border_alpha;
    // end wxGlade
}; // wxGlade: end class

class test_prefs: public wxPanel {
public:
// content of this block (ids) not found: did you rename this class?

    test_prefs(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    void set_properties();
    void do_layout();

protected:
// content of this block (attributes) not found: did you rename this class?
}; // wxGlade: end class


#endif // PREFSDIALOG_TMP_H
