// -*- C++ -*- generated by wxGlade 0.6.1 on Tue Jan 08 19:26:19 2008

#include "prefsdialog_tmp.h"

// begin wxGlade: ::extracode
// end wxGlade



test_prefs::test_prefs(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
// content of this block not found: did you rename this class?
}


void test_prefs::set_properties()
{
// content of this block not found: did you rename this class?
}


void test_prefs::do_layout()
{
// content of this block not found: did you rename this class?
}




display_prefs::display_prefs(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    wxPanel(parent, id, pos, size, wxTAB_TRAVERSAL)
{
    // begin wxGlade: display_prefs::display_prefs
    grid_styler_staticbox = new wxStaticBox(this, -1, wxT("Grid"));
    const wxString m_aspectratio_choices[] = {
        
    };
    m_aspectratio = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0, m_aspectratio_choices, 0);
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Custom:"));
    m_aspectratioX = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_2 = new wxStaticText(this, wxID_ANY, wxT(":"));
    m_aspectratioY = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    label_3 = new wxStaticText(this, wxID_ANY, wxT("Proportion of width:height ingame."));

    set_properties();
    do_layout();
    // end wxGlade
}


void display_prefs::set_properties()
{
    // begin wxGlade: display_prefs::set_properties
    m_aspectratioX->SetMinSize(wxSize(40, -1));
    m_aspectratioY->SetMinSize(wxSize(40, -1));
    label_3->SetForegroundColour(wxColour(0, 0, 85));
    // end wxGlade
}


void display_prefs::do_layout()
{
    // begin wxGlade: display_prefs::do_layout
    wxBoxSizer* top_sizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* container = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* grid_styler = new wxStaticBoxSizer(grid_styler_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(m_aspectratio, 0, wxALL, 3);
    sizer_1->Add(5, 5, 1, wxEXPAND, 0);
    sizer_1->Add(label_1, 0, wxALL|wxALIGN_CENTER_VERTICAL, 3);
    sizer_1->Add(m_aspectratioX, 0, wxALL, 3);
    sizer_1->Add(label_2, 0, wxTOP|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 3);
    sizer_1->Add(m_aspectratioY, 0, wxALL, 3);
    grid_styler->Add(sizer_1, 1, wxALL|wxEXPAND, 0);
    grid_styler->Add(label_3, 0, wxALL|wxEXPAND, 3);
    container->Add(grid_styler, 0, wxALL|wxEXPAND, 5);
    top_sizer->Add(container, 1, wxALL|wxEXPAND, 5);
    SetSizer(top_sizer);
    top_sizer->Fit(this);
    // end wxGlade
}

