// -*- C++ -*- generated by wxGlade 0.6.1 on Tue Jan 08 19:26:19 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
// end wxGlade


#ifndef PREFSDIALOG_TMP_H
#define PREFSDIALOG_TMP_H


// begin wxGlade: ::extracode
// end wxGlade








class network_prefs: public wxDialog {
public:
    // begin wxGlade: network_prefs::ids
    // end wxGlade

    network_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: network_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: network_prefs::attributes
    wxStaticBox* sizer_13_staticbox;
    wxStaticBox* sizer_12_staticbox;
    wxStaticText* network_title;
    wxCheckBox* m_startup_checkforupdate;
    wxTextCtrl* m_net_proxy;
    wxStaticText* label_8;
    // end wxGlade
}; // wxGlade: end class

class misc_prefs: public wxDialog {
public:
    // begin wxGlade: misc_prefs::ids
    // end wxGlade

    misc_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: misc_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: misc_prefs::attributes
    wxStaticBox* sizer_7_staticbox;
    wxStaticBox* sizer_2_staticbox;
    wxStaticBox* sizer_1_staticbox;
    wxStaticText* misc_title;
    wxCheckBox* m_save_backup;
    wxCheckBox* m_startup_load;
    wxStaticText* label_14;
    wxButton* button_1;
    wxCheckBox* m_elements_collections;
    wxStaticText* label_6;
    // end wxGlade
}; // wxGlade: end class


class advanced_prefs: public wxDialog {
public:
    // begin wxGlade: advanced_prefs::ids
    // end wxGlade

    advanced_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: advanced_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: advanced_prefs::attributes
    // end wxGlade
}; // wxGlade: end class


class cpma_prefs: public wxDialog {
public:
    // begin wxGlade: cpma_prefs::ids
    // end wxGlade

    cpma_prefs(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: cpma_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: cpma_prefs::attributes
    wxStaticBox* sizer_5_staticbox;
    wxStaticBox* sizer_3_staticbox;
    wxStaticText* cpma_title;
    wxStaticText* label_13;
    wxTextCtrl* m_q3_gamedir;
    wxButton* button_2;
    wxStaticText* label_12;
    wxTextCtrl* m_q3_background;
    wxButton* button_2_copy;
    wxCheckBox* m_q3_background_usedefault;
    // end wxGlade
}; // wxGlade: end class

class display_prefs: public wxPanel {
public:
    // begin wxGlade: display_prefs::ids
    // end wxGlade

    display_prefs(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: display_prefs::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: display_prefs::attributes
    wxStaticBox* grid_styler_staticbox;
    wxStaticBox* ar_styler_staticbox;
    wxStaticText* display_title;
    wxStaticText* label_3;
    wxChoice* m_view_aspectratio;
    wxStaticText* label_1;
    wxTextCtrl* m_view_aspectratio_custom;
    wxStaticText* label_2;
    wxStaticText* label_7;
    wxStaticText* label_4;
    wxSpinCtrl* m_view_gridX;
    wxStaticText* label_5;
    wxSpinCtrl* m_view_gridY;
    // end wxGlade
}; // wxGlade: end class

#endif // PREFSDIALOG_TMP_H
